### ISSUE TITLE
Feat: Dynamic wait on screenshot tests

### ISSUE THREAD

**Issue by GilbN** [linuxserver/docker-ci#34]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Dynamic wait on screenshot tests. 

Rework how we take screenshots. Today we wait a set amounts of seconds before attempting a screenshot. 

### Reason for change

Better faster stronger

**Comment by thespad** [comment]
Also ideally need a separate timeout and/or dynamic wait for the SBOM task, because some of the really big images take upwards of 10 minutes to run the SBOM catalogue and some are done in 30 seconds.
